---

- hosts: all
  become: true
  tasks:

  # Plays for all hosts
  - name: Install updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base


# Plays for web servers
- hosts: web_servers
  become: true
  roles:
    - web_servers


# Plays for db servers
- hosts: db_servers
  become: true
  roles:
    - db_servers


# Plays for file servers
- hosts: file_servers
  become: true
  roles:
    - file_servers
